spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:20}
      minimum-idle: ${HIKARI_MIN_IDLE:5}
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000

  spring:
    data:
      redis:
        host: ${SPRING_REDIS_HOST}
        port: ${SPRING_REDIS_PORT:6379}
        username: ${SPRING_REDIS_USERNAME:default}
        password: ${SPRING_REDIS_PASSWORD}
        timeout: 3000ms
        ssl:
          enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never
    include-message: always

queueless:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.queueless: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
